### ISSUE TITLE
java.lang.NumberFormatException: For input string:

### ISSUE THREAD

**Issue by daichengxin** [Nesvilab/PTM-Shepherd#18]
Hi there, I'm running PTM Shepherd CLI jar as a standalone for some reason. Here is the PTM Shepherd log in standalone, it reported these errors:

```
java.lang.NumberFormatException: For input string: ""9"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:638)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at edu.umich.andykong.ptmshepherd.localization.SiteLocalization.annotateLine(SiteLocalization.java:180)
        at edu.umich.andykong.ptmshepherd.localization.SiteLocalization.localizePSMs(SiteLocalization.java:104)
        at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:551)
Error in: b1906_293T_proteinID_01A_QE3_122212.55096.55096.3     b1906_293T_proteinID_01A_QE3_122212     YTAPQPEQCMFHDDWISSIK    YTAPQPEQC[160]M[147]FHDDWISSIK                          20      3       10218.14575     2468.082031     2468.082031     823.7012864     823.7012864     2468.077637     823.6998291     -0.004394531            31.52359815     16.76415298     0.999910499     2       0                       29654362        "9C(57.021464), 10M(15.994915)"                sp|Q9GZL7|WDR12_HUMAN                                                    Q9GZL7
java.lang.NumberFormatException: For input string: ""5"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:638)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at edu.umich.andykong.ptmshepherd.localization.SiteLocalization.annotateLine(SiteLocalization.java:180)
        at edu.umich.andykong.ptmshepherd.localization.SiteLocalization.localizePSMs(SiteLocalization.java:104)
        at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:551)
Error in: b1906_293T_proteinID_01A_QE3_122212.37851.37851.3     b1906_293T_proteinID_01A_QE3_122212     TIRPMDMETIEASVMKTIRPM[147]DMETIEASVM[147]K                              16      3       7656.333618     1882.88623      1882.88623     628.6360195      628.6360195     1882.883911     628.6352539     -0.002319336            31.51711751     0.07936573     0.999910499      2       0                       12482826        "5M(15.994915), 15M(15.994915)"                        sp|P11177|ODPB_HUMAN                                                     P11177

```

And these are the shepherd.config file and psm file. Looking forward to your help!
[inputPTMShepherd.zip](https://github.com/user-attachments/files/16974496/inputPTMShepherd.zip)

**Comment by dpolasky** [comment]
Hi,
There are quotation marks in the Assigned Modifications column for PSMs with >1 modification that are causing the issue - this often happens when saving a file from Excel. Opening the file in a text editor and replacing all " characters with nothing should resolve it. 

Best,
Dan

**Comment by daichengxin** [comment]
Thanks a lot. It's fixed.
