### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by animesh** [Nesvilab/PTM-Shepherd#4]
I am trying to run PTM-Shepherd v 0.3.4 over a linux cluster:
```
uname -a
Linux halting-armadillo-deep-learning-tools 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
and facing this error:
```
deep-learning-tools:~/PD/Animesh/MSFragger-3.0$ java -jar ptmshepherd-0.3..4.jar ptmSconf.txt 
PTM-Shepherd version 0.3.4(c) University of Michigan

Using Java 1.8.0_242 on 13564MB memory

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at edu.umich.andykong.ptmshepherd.PSMFile.getRunNames(PSMFile.java:55)
        at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:200)
```
Probably i am setting the config file incorrectly, contents of which are:
```
ash022@halting-armadillo-deep-learning-tools:~/PD/Animesh/MSFragger-3.0$ cat ptmSconf.txt
database = 2020-07-16-decoys-reviewed-contam-UP000005640.fas
dataset = 20150512_BSA_The-PEG-envelope 20150512_BSA_The-PEG-envelope.tsv /home/ash022/PD/Animesh/MSFragger-3.0

annotation_tol = 0.01
compare_betweenRuns = false
histo_bindivs = 5000
histo_smoothbins = 2
isotope_error = 0/1/2
isotope_states =
localization_background = 4
mass_offsets = 0
output_extended = false
peakpicking_mass_units = 0
peakpicking_promRatio = 0.3
peakpicking_topN = 500
peakpicking_width = 0.002
precursor_mass_units = 0
precursor_tol = 0.01
run-shepherd = true
spectra_condPeaks = 100
spectra_condRatio = 0.01
spectra_ppmtol = 20.0
threads = 23
varmod_masses = Failed_Carbamidomethylation:-57.021464
```
as the fas file was generated using philosopher:
```
~/PD/Animesh/MSFragger-3.0$ head 2020-07-16-decoys-reviewed-contam-UP000005640.fas
>rev_sp|A0A024RBG1|NUD4B_HUMAN Diphosphoinositol polyphosphate phosphohydrolase NUDT4B OS=Homo sapiens OX=9606 GN=NUDT4B PE=3 SV=1
RVSSPLGSTQAATVFLANNDPLSPVTSNGNAPSCGLKLKELYEAHVPKHCQLVKIADEVKFWERKRGINVSDEWDELIETVTLVYVYTRHKRDQNQEFIGLLRGLKGKVGAEEYVERVAAGGPEEEPEMGGGPVIWQDPYRSSSVLLVEDEQESRFCLCAARKKFGERDYTRTQNPKFKMM
>rev_sp|A0A075B6H7|KV37_HUMAN Probable non-functional immunoglobulin kappa variable 3-7 OS=Homo sapiens OX=9606 GN=IGKV3-7 PE=5 SV=1
PLNYDQQCYYVAFDEPQLSSITLTFDTGSGSGSFRAPISTARTSAGYILLRPAQGPKQQYWTLYSSSVSQSARCSLTVREGPSLSLTPPSQTMVIERTTDPLWLLLLFLLQAPAEM
>rev_sp|A0A075B6H8|KVD42_HUMAN Probable non-functional immunoglobulin kappa variable 1D-42 OS=Homo sapiens OX=9606 GN=IGKV1D-42 PE=5 SV=6
PYSFDQKCYYAAFDEPKLSIITLTFDTGSGRGSFRSSVGPHLDKADYLFLKPSKGPKQLYWALNSSIGESAWCIISVRDGVSASLFSPSQTMQIDFRVGPLWLLLLGLLQAPVRMDM
...
~/PD/Animesh/MSFragger-3.0$ tail 2020-07-16-decoys-revwed-contam-UP000005640.fas
>sp|S4R3P1|HMN13_HUMAN Humanin-like 13 OS=Homo sapiens OX=9606 GN=MTRNR2L13 PE=3 SV=1-16-decoys-rev
MDTQGFSCLLLLISEIDLSVKRRI
>sp|S4R3Y5|HMN11_HUMAN Humanin-like 11 OS=Homo sapiens OX=9606 GN=MTRNR2L11 PE=3 SV=1
MATRGFSCLLLVISEIDLSVKRWV
>sp|U3KPV4|A3LT2_HUMAN Alpha-1,3-galactosyltransferase 2 OS=Homo sapiens OX=9606 GN=A3GALT2 PE=2 SV=1
MALKEGLRAWKRIFWRQILLTLGLLGLFLYGLPKFRHLEALIPMGVCPSATMSQLRDNFTGALRPWARPEVLTCTPWGAPIIWDGSFDPDVAKQEARQQNLTIGLTIFAVGRYLEKYLERFLETAEQHFMAGQSVMYYVFTELPGAVPRVALGPGRRLPVERVARERRWQDVSMARMRTLHAALGGLPGREAHFMFCMDVDQHFSGTFGPEALAESVAQLHSWHYHWPSWLLPFERDAHSAAAMAWGQGDFYNHAAVFGGSVAALRGLTAHCAGGLDWDRARGLEARWHDESHLNKFFWLHKPAKVLSPEFCWSPDIGPRAEIRRPRLLWAPKGYRLLRN
>sp|W5XKT8|SACA6_HUMAN Sperm acrosome membrane-associated protein 6 OS=Homo sapiens OX=9606 GN=SPACA6 PE=1 SV=2
MALLALASAVPSALLALAVFRVPAWACLLCFTTYSERLRICQMFVGMRSPKLEECEEAFTAAFQGLSDTEINYDERSHLHDTFTQMTHALQELAAAQGSFEVAFPDAAEKMKKVITQLKEAQACIPPCGLQEFARRFLCSGCYSRVCDLPLDCPVQDVTVTRGDQAMFSCIVNFQLPKEEITYSWKFAGGGLRTQDLSYFRDMPRAEGYLARIRPAQLTHRGTFSCVIKQDQRPLARLYFFLNVTGPPPRAETELQASFREVLRWAPRDAELIEPWRPSLGELLARPEALTPSNLFLLAVLGALASASATVLAWMFFRWYCSGN
>sp|W6CW81|PYDC5_HUMAN Pyrin domain-containing protein 5 OS=Homo sapiens OX=9606 GN=PYDC5 PE=1 SV=1
MESKYKEILLLTSLDNITDEELDRFKCFLPDEFNIATGKLHTLNSTSSQLDLKRWHGVCSEEDRIFQKLNYMLVAKCLREEQETGICGSPSSARSVSQSRLGLSFHGISGNAC
```
and tsv is generated with msfragger:
```
:~/PD/Animesh/MSFragger-3.0$ head 20150512_BSA_The-PEG--envelope.tsv
scannum precursor_neutral_mass  retention_time  charge  hit_rank        peptide peptide_prev_aa peptide_next_aa protein num_matched_iontot_num_ions     calc_neutral_pep_mass   massdiff        num_tol_term    num_missed_cleavages    modification_info       hyperscore     nextscore        expectscore     best_locs       score_without_delta_mass        best_score_with_delta_mass      second_best_score_with_delta_mass       delta_score
97      1081.620483     0.337458        2       1       NALNEQLNAIK     K       E       rev_sp|Q66GS9|CP135_HUMAN Centrosomal protein of 135 kDa OS=Homo sapiens OX=9606 GN=CEP135 PE=1 SV=2    4       20      1226.661865     -145.041382     2       0               10.408000       10.169000       4.665648e-01    NALNEqLNAIK     7.104276        10.408113       9.060461        1.347652129     1037.592407     0.506670        2       1       IWVFSMMR        R       R       sp|Q5FWF5|ESCO1_HUMAN N-acetyltransferase ESCO1OS=Homo sapiens OX=9606 GN=ESCO1 PE=1 SV=3      4       14      1068.524780     -30.932373      2       0               9.211000       9.211000 1.666941e+00    IWVfSMMR        6.242629        9.211163        8.409586        0.801577210     1169.672607     0.806121        2       1       SVAEQAQMMR      R       V       rev_sp|Q02410|APBA1_HUMAN Amyloid-beta A4 precursor protein-binding family A member 1 OS=Homo sapiens OX=9606 GN=APBA1 PE=1 SV=3        4       18      1149.526978     20.145630      10.592000        10.347000       9.101081e-01    SVAEQAqMMR      8.179567        10.592606       9.217684        1.374922
286     1081.621826     1.163362        2       1       ANLENKLLGK      K       N       sp|Q9ULW0|TPX2_HUMAN Targeting protein for Xklp2 OS=Homo sapiens OX=9606 GN=TPX2 PE=1 SV=2      4       18      1098.639648     -17.017822      2       1               9.800000       9.800000 7.954036e-01    ANLENKLLgk      7.659870        9.800789        9.077039        0.723750289     1038.598755     1.175617        2       1       QLTKAMMR        R       K       sp|P42126|ECI1_HUMAN Enoyl-CoA delta isomerase 1, mitochondrial OS=Homo sapiens OX=9606 GN=ECI1 PE=1 SV=1       5       14      977.515076      61.083679       2       1              10.544000        10.118000       9.800439e-01    QLTkAMMR        6.612432        10.544214       9.340633        1.203581338     1360.874756     1.405751        2       1       GQLRLLENDSR     R       E       sp|Q8TE82|S3TC1_HUMAN SH3 domain and tetratricopeptide repeat-containing protein 1 OS=Homo sapiens OX=9606 GN=SH3TC1 PE=1 SV=3  4       20      1299.689453     61.185303       2      4.401000 4.401000        1.058644e+00    GQLRLLENDsr     3.028877        4.401579        3.587921        0.813658450     1216.708984     1.854977        2       1       IVNAVVSYIK      K       G       sp|Q5VUY2|ADCL4_HUMAN Arylacetamide deacetylase-like 4 OS=Homo sapiens OX=9606 GN=AADACL4 PE=3 SV=1     6       18      1104.654175     112.054810      2       0               13.274000       11.760000       1.797662e-03    iVNAVVSYIK      7.956193        13.274450       11.794912       1.479538487     1169.673340     2.049713        2       1       SVAEQAQMMR      R       V       rev_sp|Q02410|APBA1_HUMAN Amyloid-beta A4 precursor protein-binding family A member 1 OS=Homo sapiens OX=9606 GN=APBA1 PE=1 SV=3        4       18      1149.526978     20.146362      10.661000        10.023000       8.127531e-01    SVAEQAqMMR      8.443073        10.661566       9.196566        1.465000499     1081.620728     2.088216        2       1       NALNEQLNAIK     K       E       rev_sp|Q66GS9|CP135_HUMAN Centrosomal protein of 135 kDa OS=Homo sapiens OX=9606 GN=CEP135 PE=1 SV=2    4       20      1226.661865     -145.041138     2       0               10.495000       9.964000        1.005297e+00    NALNEqLNAIK     6.944489        10.495222       9.207600        1.287622
```
so i guess that should not be an issue?

**Comment by danielgeiszler** [comment]
Hey @animesh 

The .tsv file you're looking at is actually the localization file produced by MSFragger, not the final filtered results. PTM-Shepherd takes the psm.tsv file produced by philosopher, which contains filtered results from the entire pipeline.

Do you have another .tsv file? it probably has the name "psm.tsv." The first column should be labeled "Spectrum".

Maybe we should consider renaming this to avoid confusion :)

**Comment by animesh** [comment]
No i don't see psm.tsv being generated but then i am just using MSFragger which seems to generate <filename>.pepXML and <filename>.tsv... what should be the filtering step in between to get from this .tsv to the shepherd friendly version :)

**Comment by animesh** [comment]
Looks like the follow
```
  ./philosopher peptideprophet --database 2020-07-17-decoys-contam-UP000005640.fas --ppm --accmass --expectscore --decoyprobs --nonparam 20150512_BSA_The-PEG-envelope.pepXML 
 ./philosopher proteinprophet interact-20150512_BSA_The-PEG-envelope.pep.xml 
  ./philosopher filter --razor --pepxml interact-20150512_BSA_The-PEG-envelope.pep.xml --protxml interact.prot.xml 
 ./philosopher report
```
has done the magic 👍 
and 
`java -jar ptmshepherd-0.3.4.jar ptmSconf.txt 
`went flawless AFAIK:
```
deep-learning-tools:~/PD/QE_ptm$ head global.modsummary.tsv 
Modification    Theoretical Mass Shift  default-ptmshepherd-dataset (PSMs) default-ptmshepherd-dataset (PSMs/million)
Iodoacetamide derivative/Addition of Glycine/Addition of G      57.021464  85      10854.3100
ubiquitinylation residue/Double Carbamidomethylation/Addition of N114.042927       45      5746.4000
None    0.0     28      3575.5300
Failed_Carbamidomethylation/Deletion of G       -57.021464      243064.7900
First isotopic peak     1.003355        13      1660.1000
Unannotated mass-shift 96.0332  96.0332 11      1404.6800
Unannotated mass-shift 339.2446 339.2446        9       1149.2900
Unannotated mass-shift 483.3240 483.324 9       1149.3000
Formylation     27.994915       5       638.4900
```
wondering how to change the --razor to --unique, as is, i am guessing razor are being included for inference?

**Comment by danielgeiszler** [comment]
Perfect!

It looks like you used closed search parameters for peptideprophet and proteinprophet, so you may want to redo those with more appropriate parameters to make sure you get the best results. You can find them in FragPipe.

**Comment by anesvi** [comment]
It is currently not possible to remove shared peptides from protein inference (filter command). But you can see in PSM.tsv files what peptides are unique or shared. Shared peptides can also be removed at the Quant stage.
Alexey
